### ISSUE TITLE
Clean up RayJobClient on timeout to prevent dangling RayJobs

### ISSUE THREAD

**Issue by ma9o** [danielgafni/dagster-ray#52]
When a RayJobClient operation times out, we currently don't call terminate() on the client. This leaves dangling Ray jobs in the cluster that continue consuming resources even if the Dagster materialization fails.

Is this intended? Should the termination be handled by the caller?

**Comment by danielgafni** [comment]
Hey, no, that's probably not expected. What component are you referring to?

**Comment by ma9o** [comment]
I'm actually starting `pipes_kube_rayjob_client.run` just as in the README but I saw the timeout logic is in the RayJobClient. 

I'm getting a `TimeoutError: Timed out waiting for RayJob ray/conversations-embeddings deployment to become available. Status:
Initializing` from time to time, and then I have to go and manually delete the dangling `rayjob` in the terminal.

**Comment by danielgafni** [comment]
So [this](https://github.com/danielgafni/dagster-ray/blob/master/dagster_ray/kuberay/pipes.py#L118) isn't happening for you?  

Also, can you increase the timeout parameter?

**Comment by danielgafni** [comment]
Hey, I just checked and the `timeout` parameter [is already there](https://github.com/danielgafni/dagster-ray/blob/master/dagster_ray/kuberay/pipes.py#L51)

Does this solve your problem?

**Comment by ma9o** [comment]
I could increase the timeout for the time being, but perhaps it would still make sense to `terminate()` [here](https://github.com/danielgafni/dagster-ray/blob/master/dagster_ray/kuberay/client/rayjob/client.py#L84)?

**Comment by danielgafni** [comment]
oh I see what you mean, sure
