### ISSUE TITLE
consume_job_logs errors

### ISSUE THREAD

**Issue by serriaguirregaray** [danielgafni/dagster-ray#55]
- `consume_job_logs` fails with default client due to `client.tail_job_logs` not being present. 

- `blocking=False` is not handling messages (there's a comment for this error already).

Haven't found the bug yet but I've found that it only works for me if  use `blocking=False` and add this change:

```
         job_submission_client = self.client.ray_cluster_client.job_submission_client(
                name=self.client.get_ray_cluster_name(name=name, namespace=namespace),
                namespace=namespace,
                port_forward=self.port_forward,
            )
            self._job_submission_client = job_submission_client
```

Instead of:

```
         with self.client.ray_cluster_client.job_submission_client(
                name=self.client.get_ray_cluster_name(name=name, namespace=namespace),
                namespace=namespace,
                port_forward=self.port_forward,
            ) as job_submission_client:
                self._job_submission_client = job_submission_client
```

**Comment by serriaguirregaray** [comment]
The error shows up sometimes with the `blocking=False`, but I still can't really use that option anyway.

The weird part is that with `blocking=True` it doesn't work at all, no errors or anything just doesn't pass logs. And it doesn't stop either once the job succeeds. I am creating it this way just with defaults:

```
result = PipesKubeRayJobClient().run(context=context, ray_job=ray_configs).get_custom_messages()
```

I couldn't create it with a JobSubmissionClient because I don't have any address yet until it runs. Maybe I'm missing something?

**Comment by danielgafni** [comment]
Are you running locally? In this case you probably want to set `PipesKubeRayJobClient(port_forwarding=True)`

**Comment by serriaguirregaray** [comment]
Thank you Daniel!

**Comment by danielgafni** [comment]
Oh, so is everything working with `port_forward=True`?
