### ISSUE TITLE
best practice for `ray_executor` workaround

### ISSUE THREAD

**Issue by gunsodo** [danielgafni/dagster-ray#58]
I find the executor so easy-to-use with the existing DAG implementation - only need to pass the executor to `@job` decorator or via the `Definitions`. This allows dynamically choosing whether to use the executor or not without creating a new job that uses `PipesRayJobClient`. However, as clearly stated in the README file, specifically in the *Feature Matrix*, `ray_executor` is not supposed to be used when the cluster does not have access to the Dagster instance.

In our settings, we have a separate Ray cluster deployed for general purposes. What would be the recommended approach so that the cluster can interact with Dagster's metadata DB?

@danielgafni Once again, thank you for such a great Dagster integration package!

**Comment by gunsodo** [comment]
@danielgafni We have setup a dedicated postgres database which is accessible from both the Ray cluster and the Dagster instance. Both instances share the same `dagster.yaml` which makes the `ray_executor` works fine. But I wonder if this is the best practice - by keeping the contents of `dagster.yaml` - in synchronization?

**Comment by danielgafni** [comment]
Yes, I think it's completely fine as long as you have well-defined CI/CD processes which take care of deployment (and `dagster.yaml` synchronization). 

What exactly is your issue then?

**Comment by gunsodo** [comment]
I was skeptical if `dagster.yaml` synchronization violates any Dagster philosophy and your answer is it does not. Thank you once again for your prompt reply and for building this :)

**Comment by danielgafni** [comment]
Another option is to use Ray's `working_dir` to pass the current `dagster.yaml` to the executor. This should work if you are using the `RayRunLauncher`.
